### ISSUE TITLE
[BUG] System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.

### ISSUE THREAD

**Issue by WoLpH** [yllibed/Zigbee2MqttAssistant#104]
**Describe the bug**

The interface doesn't show any devices and the console keeps repeating these errors:
```
# docker run -p 8400:80 -e Z2MA_SETTINGS__MQTTSERVER=mqtt -e Z2MA_SETTINGS__MQTTUSERNAME='' -e Z2MA_SETTINGS__MQTTPASSWORD='' --restart always carldebilly/zigbee2mqttassistant
Starting Zigbee2MqttAssistant v0.3.88+Branch.master.Sha.a34fe059880e14ed9862286d6aa30d3853b87009...
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {d76e1e81-1147-468d-abd5-ebbb7833b9e8} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String payload) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 459
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 315
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String payload) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 459
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 315
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String payload) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 459
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 315
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 59
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String payload) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 459
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 315
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
```

**To Reproduce**

1. Start Zigbee2MqttAssistant (via Docker)
2. See errors

**Installation**
 - Version of Zigbee2Mqtt: Updated 10 minutes ago, commit: e26ad2aca2eeb0aa366982481eb921ee603fb6d1
 - Version of Zigbee2MqttAssistant: Latest docker, pulled 10 minutes ago
 - Installation type: Docker
 - Docker version: Docker version 19.03.4, build 9013bf583a, amd64

**Comment by carldebilly** [comment]
This was an error while trying to report an error.. :-S

Please try again with latest dev version (v0.3.97+) using the following command line:
```
docker run -p 8400:80 <env parameters> --restart always carldebilly/zigbee2mqttassistant:dev
```

Using the latest `carldebilly/zigbee2mqttassistant:dev` image will pull the right image.

... and you'll be able to see the real problem.

**Comment by carldebilly** [comment]
@all-contributors please add WoLpH to bugs

**Comment by WoLpH** [comment]
Thank you for the quick response!

Here's the new and improved stacktrace:
```
Starting Zigbee2MqttAssistant v0.3.98+Branch.master.Sha.c252e75b8054cacd25abb14345ea90b6a3f3a1cc...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {f6ce6ae2-b315-4e50-b7f5-cfbfa92a16c8} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474734408... -- will be ignored.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474738429... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474742439... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474746457... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474750460... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474754465... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474758467... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474762470... -- will be ignored.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474766479... -- will be ignored.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1572474770482... -- will be ignored.
```

**Comment by WoLpH** [comment]
I should note that it does appear to be mostly working now. The interface is loading the devices

**Comment by carldebilly** [comment]
Still have problems?  It's very curious what you have.  It's like a unix timestamp (ex: `1572474762` is the unix timestamp for `2019-10-30 - 22:32`).

I can't imagine why you are receiving such data on the [`zigbee2mqtt/bridge/config/devices` topic](https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigdevicesget). That's very weird.

**Comment by carldebilly** [comment]
It should be compatible. I should try it to understand why it's happening.

**Comment by WoLpH** [comment]
It's definitely a bug on the side of zigbee2mqttadminpanel. It's fighting with zigbee2mqtt to overwrite that key constantly.

In any case, the bug is not on your side of things :)
