### ISSUE TITLE
[BUG] Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'

### ISSUE THREAD

**Issue by tiagofreire-pt** [yllibed/Zigbee2MqttAssistant#109]
# Describe the bug
Error processing topics.

## To Reproduce

1. Just run plain vanilla zigbee2mqttassistant

**Expected behavior**
No such errors.

## Steps I took to try resolve the problem
Restart the add-on

## Screenshots
N/A

## Installation
 - Version of Zigbee2Mqtt: 1.6.0
 - Version of Zigbee2MqttAssistant: Lastest
 - Installation type (HASS.IO, Docker...): Hass.io
 - Docker version + CPU type (amd64, arm arm64...): N/A

## Pertinent logs
```
Starting Zigbee2MqttAssistant v0.3.88+Branch.master.Sha.a34fe059880e14ed9862286d6aa30d3853b87009...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another devices request already in progress.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 59
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 59
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
```

## Additional context
N/A

**Comment by carldebilly** [comment]
Z2MA shouldn't process those messages. But processing them with error should not affect the stability on the software. Do you see other impact than an error in the log output?

**Comment by tiagofreire-pt** [comment]
@carldebilly, other than spamming the log and resulting on failure messages, possibly, would be better to code an ignore routine for those ones. As the other component/add-on is massively used combined with this one, leading the end-user to a misleading interpretation.

**Comment by carldebilly** [comment]
I agree on this...  I was just wondering if you noticed any other impact...

**Comment by Electronlibre2012** [comment]
Hello @tiagofreire-pt ,

same for me,

restart the add on delete messages, i dont see anything working wrong in my sensors.

Now it works normaly since 6 hours, and this morning i have "no response since 4 days" in each sensor on the main page...

**Comment by carldebilly** [comment]
@Electronlibre2012 
If you restart the add-on, it's going back to correct measurements? Any warning in the log?

**Comment by Electronlibre2012** [comment]
Hello @carldebilly 

thanks for your help,

i have no warning in Zigbee2mqtt, just a warning in Zigbee2mqttAssistant : 
```
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
```

and tu reply after restart, some of the sensor are ok, others not... :




![Bug](https://user-images.githubusercontent.com/49882201/69059447-fac1ce00-0a2e-11ea-8147-6bee81b2018b.png)

Its completly different each time i restart the addon...

**Comment by Electronlibre2012** [comment]
UP :

after i restart the addon zigbee2mqttAssistant, all sensor respond ok

**Comment by carldebilly** [comment]
Ok.  I know this problem. I'll try to fix it in the coming days.

**Comment by Electronlibre2012** [comment]
Hello @carldebilly ,

any news about this please?

Still have all my device "unresponsive s. 4 weeks" lol

Every time i restart its ok...for 5 minutes...or less

Strange thing is it never happened for the coordinator and i install a router zigbee with a CC2530 two days ago and the router is always responsive, no problem, it seems this bug only affect the sensors...but perhaps i m wrong...if it could help...

Thanks! have a nice week end

**Comment by carldebilly** [comment]
Sorry, it's x-mas time and very busy. I'll try to fix soon.

**Comment by Electronlibre2012** [comment]
Ok thanks, Happy Christmas

**Comment by CodeFinder2** [comment]
I am facing the same issue. :see_no_evil:

**Comment by carldebilly** [comment]
Please test with latest `dev` version :-)

**Comment by Electronlibre2012** [comment]
thanks! ill try and come back soon

Le lun. 30 déc. 2019 à 09:34, Carl de Billy <notifications@github.com> a
écrit :

**Comment by CodeFinder2** [comment]
I just realized that Z2MA was not running anymore, see the following log, so it still seems to be a problem :see_no_evil: :
```text
Log
Starting Zigbee2MqttAssistant v0.3.131+Branch.master.Sha.88dd75f0cf80c8795e6b2b4300bfafaa8b8a5575...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 125
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 435
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 342
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
```

Or is it possible that something different than what is shown in the log has caused the crash? :thinking:

**Comment by carldebilly** [comment]
That is not a crash. It's just a fail to parse something.
It should has been fixed... strange. I'll reopen it.

**Comment by CodeFinder2** [comment]
Yeah, it's indeed not a crash but I thought this error message / parser error should have gone away already. :see_no_evil: I don't know how to reproduce it, tried a few times but it doesn't show up again. :thinking: 

I'll report back if I have any news rgd. this issue. At least up to now, Z2MA didn't exited unexpectedly again. :smiley:

**Comment by CodeFinder2** [comment]
Hmmm: it just crashed, having this in my log

```text
Starting Zigbee2MqttAssistant v0.3.133+Branch.master.Sha.f490bd70a0401bc6d96a4d02d5f9022a43bb5e9e...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 125
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 435
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 342
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 125
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 435
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 342
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
```

**Comment by Electronlibre2012** [comment]
Hello, same here

**Comment by carldebilly** [comment]
Thanks @magpern for your involvement in this project!
