### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by Freubelaar** [yllibed/Zigbee2MqttAssistant#115]
Hi Guys,

Need some help, I got a fail message in my log. see info below, I hope its complete

Error message:
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]

zigbee2mqtt version 1.7
HA version 101.3

zigbee2mqttassistant config:
{
"settings": {
"base_topic": "zigbee2mqtt",
"homeassistant": true,
"mqttserver": "core-mosquitto",
"MqttPort": 1883,
"MqttSecure": false,
"mqttusername": " ",
"mqttpassword": " ",
"LowBatteryThreshold": 25
}
}

Log zigbee2mqttassistant:
Starting Zigbee2MqttAssistant v0.3.88+Branch.master.Sha.a34fe059880e14ed9862286d6aa30d3853b87009...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
at System.String.Substring(Int32 startIndex, Int32 length)
at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String payload) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 459
at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 315
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/devices'
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
at System.String.Substring(Int32 startIndex, Int32 length)
at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevices(String payload) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 322
at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchDevicesMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 459
at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 315

**Comment by carldebilly** [comment]
Please try the "DEV" version to see if you have the same problem...

**Comment by Freubelaar** [comment]
Installed DEV with same config.

Log files below:

Starting Zigbee2MqttAssistant v0.3.100+Branch.master.Sha.b167e24030e18bd0b659582d1716d06cd4a3cc38...
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {2b747773-bc9e-449b-8fcc-820305662e0c} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/groups'
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 13.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1573639489546... -- will be ignored.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/groups'
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 13.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1573639493546... -- will be ignored.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/groups'
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 13.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 328
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Invalid/unknown devices payload received. root element type is Integer: 1573639497547... -- will be ignored.

**Comment by carldebilly** [comment]
This is a known problem. A fix is coming.  But it's more it's failing to process some that should be ignored.  Shouldn't have a impact on the add-on... may you confirm?

**Comment by Freubelaar** [comment]
Yes, I can confirm that, the Add-on is working normal.

**Comment by carldebilly** [comment]
Seems related to another Z2M console (node-red?). Is it possible?

**Comment by Freubelaar** [comment]
I have running that one ues. Will check out tomorrow for more info

**Comment by carldebilly** [comment]
... and?
