### ISSUE TITLE
[BUG] unresponsive s. 4 days

### ISSUE THREAD

**Issue by Electronlibre2012** [yllibed/Zigbee2MqttAssistant#119]
# Describe the bug

Hello, all my sensor, like button, motion, led light and AC socket (from Xiaomi) are all marked as "unresponsive s. 4 days" but i received update avery 10-20 minutes, all seems to work correctly...
## To Reproduce

**Expected behavior**

Because, all my sensors work and gives states or values, or actions, why are they marked "unresponsive s. 4 days"
## Installation
 - Version of Zigbee2Mqtt: 1.7.1
 - Version of Zigbee2MqttAssistant: 0.3.105
 - Installation type (HASS.IO, Docker...): hassio
 - Docker version + CPU type (amd64, arm arm64...): Rpi4 4Go

## Pertinent logs

fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 125
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 405
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 341

**Comment by Electronlibre2012** [comment]
restart of the addon zigbee2mqttAssistant solved temporaly the problem

**Comment by carldebilly** [comment]
Should be fixed by https://github.com/yllibed/Zigbee2MqttAssistant/pull/148

**Comment by carldebilly** [comment]
Should be fixed by Z2MA v`0.3.122`. Check on the "dev" channel.
