### ISSUE TITLE
Unable to rename entity

### ISSUE THREAD

**Issue by johntdyer** [yllibed/Zigbee2MqttAssistant#122]
# Describe the bug
Unable to rename an entity, tried multiple times after restart of both the assistant app and the zigbee2mqtt app

## To Reproduce
Open entity
Rename entity

**Expected behavior**

I expect to be able to rename an entity

## Installation
 - Version of Zigbee2Mqtt:  1.7.1
 - Version of Zigbee2MqttAssistant: 0.3.103
 - Installation type (HASS.IO, Docker...): Hassio
 - Docker version + CPU type (amd64, arm arm64...):
Amd64

## Pertinent logs

```

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Another rename in progress for this device.
   at Zigbee2MqttAssistant.Services.MqttConnectionService.RenameDeviceAndWait(String deviceFriendlyName, String newName) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 611
   at Zigbee2MqttAssistant.Services.BrigeOperationService.RenameDeviceById(String deviceId, String newName) in d:\a\1\s\Zigbee2MqttAssistant\Services\BrigeOperationService.cs:line 42
   at Zigbee2MqttAssistant.Controllers.HomeController.RenameDevice(String id, String newName) in d:\a\1\s\Zigbee2MqttAssistant\Controllers\HomeController.cs:line 93
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by carldebilly** [comment]
The message is `Another rename in progress for this device.`. You may need to restart Z2MA. It could happend if you tried to launch a rename while Z2M was offline or if an error happen during renaming... since there's no possibility to know the rename didn't work.

I should add a delay... in the mean time, you need to restart Z2MA.

Thanks for reporting!
@all-contributors please add johntdyer to bugs

**Comment by carldebilly** [comment]
@all-contributors please add johntdyer to bug

**Comment by carldebilly** [comment]
The required change has been merged in Z2M. Already available in "dev" version, You may want to test it or wait for it to be available in stable release.
