### ISSUE TITLE
help wanted: docker image fails  at startup

### ISSUE THREAD

**Issue by eeevs** [yllibed/Zigbee2MqttAssistant#128]
Is there any documation  how to set this up.  I installed the docker images and got problems.
I got a fail at startup and it doesnt work. Any suggestion how do I solve this?

warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic home-assistant/woonkamer in entity 0x00158d00025f1dc2-sensor-humidity.
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {fde4bddd-1959-4309-a9d5-f2eab760d932} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

I got this a warning for all my zigbee devices.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name

Any suggestion how to solve this?
Thanks.
EVS.

**Comment by carldebilly** [comment]
Is it causing Z2MA to fail or it's just error messages in the output?

**Comment by GrumpyMeow** [comment]
Weird. The Docker-image does start without a problem on my Ubuntu-docker-server.
Did you give a friendly name to the specific device?
The actual error does give some speicific information: Unable to find friendly name from topic home-assistant/woonkamer in entity 0x00158d00025f1dc2-sensor-humidity.

**Comment by carldebilly** [comment]
@GrumpyMeow @eeevs Is Z2MA working correctly or not?

**Comment by eeevs** [comment]
No. When  the Docker contianer is not working correctly for some reason. There not much you can do other then uninstall it. There is no way I can debug this.
