### ISSUE TITLE
[BUG] No mapping data / unable to scan the network

### ISSUE THREAD

**Issue by adrianmihalko** [yllibed/Zigbee2MqttAssistant#162]
## Installation
 - Version of Zigbee2Mqtt:
1.80
 - Version of Zigbee2MqttAssistant:
0.3.122
 - Installation type (HASS.IO, Docker...):
HASS.IO
 - Docker version + CPU type (amd64, arm arm64...):

## Additional context

I have some questions:

1. On Map I can't see relations between devices:

<img width="979" alt="Screenshot 2020-01-13 at 20 29 16" src="https://user-images.githubusercontent.com/733361/72285432-639a8080-3643-11ea-97f8-f826801feb30.png">

In Log I see failures and warnings problems: 

```
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/networkmap/graphviz'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: d. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 435
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 342
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
```

2. It is normal that link quality is null in the details?

<img width="239" alt="Screenshot 2020-01-13 at 20 35 35" src="https://user-images.githubusercontent.com/733361/72285859-47e3aa00-3644-11ea-90f0-5810ba0daa45.png">

**Comment by carldebilly** [comment]
You should try to restart Z2MA and upgrade to latest "dev" version.

When there's another scan in progress, it won't launch another one, preventing any result.  That way you're just seeing your devices without the mapping data.
