### ISSUE TITLE
[BUG] Z2MA crashed (process stopped)

### ISSUE THREAD

**Issue by michelebossa** [yllibed/Zigbee2MqttAssistant#177]
# Describe the bug
Hi,
I have a problem with a lot of these message "Another network scan request already in progress."  into log ant the map do not contain any connection between entity anymore.
Thanks for the help.
## To Reproduce

**Expected behavior**

## Screenshots

![image](https://user-images.githubusercontent.com/38975058/73933613-1bd2e600-48dd-11ea-8259-57e8beb7264c.png)

![image](https://user-images.githubusercontent.com/38975058/73933714-55a3ec80-48dd-11ea-8610-657104737405.png)

## Installation
 - Version of Zigbee2Mqtt: 1.10.0
 - Version of Zigbee2MqttAssistant: 0.3.133
 - Installation type (HASS.IO, Docker...): Docker
 - Docker version + CPU type (amd64, arm arm64...): Rasp PI 2

**Comment by CodeFinder2** [comment]
Me too. And Z2MA crashed a few times now after showing that error. 😕

**Comment by carldebilly** [comment]
It crashed?  I mean... Z2MA stopped working?

**Comment by CodeFinder2** [comment]
Unfortunately, yes. I needed to press the addon's 'Start' button to use it again. Can this possibly happen when Z2M is restarted? (I did that a lot in the recent past to debug other issues but sure if this was related.)

**Comment by CodeFinder2** [comment]
Have just seen that it is off again...Log:
```text
Starting Zigbee2MqttAssistant v0.3.137+Branch.master.Sha.302c5a05043a021884e9babdda6fb7564f998039...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Immutable.ImmutableArray`1.get_Length()
   at System.Collections.Immutable.ImmutableArray`1.Replace(T oldValue, T newValue, IEqualityComparer`1 equalityComparer)
   at System.Collections.Immutable.ImmutableArray`1.Replace(T oldValue, T newValue)
   at Zigbee2MqttAssistant.Services.BridgeStateService.<>c__DisplayClass19_2.<UpdateNetworkMap>b__5(ImmutableArray`1 parents) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 493
   at Zigbee2MqttAssistant.Models.Devices.ZigbeeDevice.Builder.WithParents(Func`2 valueSelector) in d:\a\1\s\Zigbee2MqttAssistant\obj\Release\netcoreapp3.0\g\ImmutableGenerator\ZigbeeDevice_65264D47.g.cs:line 744
```

**Comment by carldebilly** [comment]
Did you try latest `dev` version?
Are you able to make a repro?  is it following an operation like a rename or a device removal?

**Comment by CodeFinder2** [comment]
> Did you try latest `dev` version?
> Are you able to make a repro? is it following an operation like a rename or a device removal?

Unfortunately, no. I was hoping that the log already helps you. I just have seen this in the log when I realized that z2ma was not running anymore. I cannot remember doing anything specific previously. I know that this is kinda useless for debugging. Will add more information if I have (especially when/if I was able to reproduce it)!

**Comment by CodeFinder2** [comment]
Another crash, Log:
```text
Starting Zigbee2MqttAssistant v0.3.137+Branch.master.Sha.302c5a05043a021884e9babdda6fb7564f998039...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Another network scan request already in progress.
Unhandled exception.Unhandled exception.  System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Zigbee2MqttAssistant.Services.MqttConnectionService.<>c__DisplayClass13_0.<<StartPolling>g__PollingDevicesTask|1>d.MoveNext() in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Zigbee2MqttAssistant.Services.MqttConnectionService.<>c__DisplayClass13_0.<<StartPolling>g__PollingNetworkTask|2>d.MoveNext() in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
IIRC, I just stopped and restarted Z2M.

And, yes it really crashed (stopped):
![Screenshot_20200211-195553](https://user-images.githubusercontent.com/20599588/74268679-8d10ff80-4d08-11ea-87ea-7988fc1fde7b.jpg)

**Comment by carldebilly** [comment]
Please try new version 0.3.138 :-) Should be fixed!

**Comment by michelebossa** [comment]
I have used the dev branch e now i can see my network map. 

Thanks alot

![image](https://user-images.githubusercontent.com/38975058/74316848-9b97ff00-4d7a-11ea-801b-296ed0df734c.png)

**Comment by CodeFinder2** [comment]
Great, thank you! 🙂

**Comment by CodeFinder2** [comment]
Z2MA is running fine for a few days now, great work, thank you again! 🙂
