### ISSUE TITLE
Z2M 'output' variable configuration cause errors

### ISSUE THREAD

**Issue by paulianttila** [yllibed/Zigbee2MqttAssistant#225]
When zigbee2mqtt 'output' configuration variable is set to attribute or attribute_and_json, following errors are logged by the assistant as topic is not json data:

```
zigbee2mqttAssistant    | fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
zigbee2mqttAssistant    |       Error processing MQTT message on topic 'zigbee2mqtt/0x7cb03eaa00aca201/linkquality'
zigbee2mqttAssistant    | Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 2.
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410
zigbee2mqttAssistant    | fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
zigbee2mqttAssistant    |       Error processing MQTT message on topic 'zigbee2mqtt/0x7cb03eaa00aca201/last_seen'
zigbee2mqttAssistant    | Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing number: T. Path '', line 1, position 10.
zigbee2mqttAssistant    |    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
zigbee2mqttAssistant    |    at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
zigbee2mqttAssistant    |    at Newtonsoft.Json.JsonTextReader.ParseValue()
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410
zigbee2mqttAssistant    | fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
zigbee2mqttAssistant    |       Error processing MQTT message on topic 'zigbee2mqtt/0x7cb03eaa00aca201/update_available'
zigbee2mqttAssistant    | Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Boolean. Path '', line 1, position 4.
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
zigbee2mqttAssistant    |    at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410

```

**Comment by magpern** [comment]
Interesting!!! Smells related to #109

**Comment by carldebilly** [comment]
Thanks @magpern for your involvement in this project!
