### ISSUE TITLE
[BUG]  HELPme  erro

### ISSUE THREAD

**Issue by yhwl8888** [yllibed/Zigbee2MqttAssistant#255]
# Describe the bug

## To Reproduce

**Expected behavior**

## Installation
 - Version of Zigbee2Mqtt:
 - Version of Zigbee2MqttAssistant:
 - Installation type (HASS.IO, Docker...):
 - Docker version + CPU type (amd64, arm arm64...):

## Pertinent logs

   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 144
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 503
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 410
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/config/groups'
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 13.

**Comment by yhwl8888** [comment]
Versions
Version of Zigbee2MqttAssistant (this software): 0.3.147 (0.3.147+Branch.master.Sha.92d831d1df50a48c4a2fd38c201e9465dc7e88dd) Release
Version of Zigbee2Mqtt: 1.12.2
Coordinator version: 20190523
Coordinator Zigbee Id:

**Comment by carldebilly** [comment]
Please try again with latest "dev" versions, it may be fixed.
