### ISSUE TITLE
docker installation: unable to connect to mqtt

### ISSUE THREAD

**Issue by minix5** [yllibed/Zigbee2MqttAssistant#27]
Hi,

a very cool project!
It seems that the key is not present in the keychain (docker image):

Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted. ---> System.Security.Cryptography.CryptographicException: The key {97c6bac4-872b-48cb-ad74-a95997dde53e} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
Application is shutting down...
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Disconnected from MQTT server mqtt.

thanks and best regards

**Comment by minix5** [comment]
... after activating "homeassistant: true" in the Zigbee2Mqtt configuration, I could see logfile messages like "warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]".
      Unable to find friendly name from topic zigbee2mqtt"
but there was no device in the web frontend and the message is: "Status Bridge State: offline"

What can I change?
Thank you for your feedback.

**Comment by carldebilly** [comment]
Hi @minix5, for your first message - about the key ring, that's something supposed to be fixed in last version (`0.2.0-dev.66`). Which version are you using?

For your second problem, you should ensure both topics (`BaseTopic` & `HomeAssistantDiscoveryBaseTopic` - <https://github.com/yllibed/Zigbee2MqttAssistant#settings>) are set to the one defined in _Zigbee2Mqtt_ (`mqtt:` / `base_topic` & `advanced` / `homeassistant_discovery_topic` - <https://www.zigbee2mqtt.io/configuration/configuration.html>).  Default values on _Zigbee2MqttAssistant_ are defined to the same default values in _Zigbee2Mqtt_.
