### ISSUE TITLE
zigbee2mqttassistant-dev can't work. I don't know the reason. Pleas help.

### ISSUE THREAD

**Issue by LovelyMengstar** [yllibed/Zigbee2MqttAssistant#277]
Starting Zigbee2MqttAssistant v0.3.169+Branch.master.Sha.48ff2dac0c4350a5c38ce4968c5f75a97dcb2a9d...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {fd934667-671b-40dc-b167-d2bd4ad9983d} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Disconnected from MQTT server 192.168.0.110.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Disconnected from MQTT server 192.168.0.110.

**Comment by carldebilly** [comment]
This error should not have impact on the operations of Z2MA (dev or not). What kind of problem are you experiencing?

**Comment by Machaeon** [comment]
Have same issue. Devices list and map are empty.
