### ISSUE TITLE
Unhandled exception. System.MissingMethodException: Method not found: 'MQTTnet.Diagnostics.IMqttNetLogger [BUG]

### ISSUE THREAD

**Issue by munklinde** [yllibed/Zigbee2MqttAssistant#292]
# Describe the bug

Service is not starting

## To Reproduce

1. Configure service, with correct access to MQTT server
2. Start service

**Expected behavior**

Service should be running

## Steps I took to try resolve the problem

None

## Installation
 - Version of Zigbee2Mqtt: 1.9.0-dev (commit #cf1bb386ead98a78b6b3bfed01e8d151cc7e9c6c)
 - Version of Zigbee2MqttAssistant: v0.3.173+Branch.master.Sha.c60890a6ffb3bb25fa2ec558499bd173ee6a3b42..
 - Installation type (HASS.IO, Docker...): HASSIO
 - Docker version + CPU type (amd64, arm arm64...):

## Pertinent logs

```
Starting Zigbee2MqttAssistant v0.3.173+Branch.master.Sha.c60890a6ffb3bb25fa2ec558499bd173ee6a3b42...
Unhandled exception. System.MissingMethodException: Method not found: 'MQTTnet.Diagnostics.IMqttNetLogger MQTTnet.Diagnostics.IMqttNetLogger.CreateChildLogger(System.String)'.
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient..ctor(IMqttClient mqttClient, IMqttNetLogger logger)
   at MQTTnet.Extensions.ManagedClient.MqttFactoryExtensions.CreateManagedMqttClient(IMqttFactory factory)
   at Zigbee2MqttAssistant.Services.MqttConnectionService.Connect() in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 117
   at Zigbee2MqttAssistant.Services.MqttConnectionService.StartAsync(CancellationToken ct) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 62
   at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Zigbee2MqttAssistant.Program.Main(String[] args) in d:\a\1\s\Zigbee2MqttAssistant\Program.cs:line 1
```

**Comment by tedsluis** [comment]
I experience the same issue:
```
Jun 22 17:58:08  docker[14348]: linux-x64: Pulling from carldebilly/zigbee2mqttassistant                                                                                                                                      
Jun 22 17:58:08  docker[14348]: Digest: sha256:df81f0d89dfc4cfc4c796ce2c768d799a7f9d65a826a23188fbd23f5b64e316e                                                                                                               
Jun 22 17:58:08  docker[14348]: Status: Image is up to date for carldebilly/zigbee2mqttassistant:linux-x64                                                                                                                    
Jun 22 17:58:08  docker[14348]: docker.io/carldebilly/zigbee2mqttassistant:linux-x64                                                                                                                                          
Jun 22 17:58:08  systemd[1]: Started zigbee2mqttassistant.service.
Jun 22 17:58:08  docker[14365]: Starting Zigbee2MqttAssistant v0.3.173+Branch.master.Sha.c60890a6ffb3bb25fa2ec558499bd173ee6a3b42...
Jun 22 17:58:09  docker[14365]: warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
Jun 22 17:58:09  docker[14365]:       Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
Jun 22 17:58:09  docker[14365]: warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
Jun 22 17:58:09  docker[14365]:       No XML encryptor configured. Key {4efe9f0e-106b-475a-8dbb-e581b6cf0f06} may be persisted to storage in unencrypted form.
Jun 22 17:58:09  docker[14365]: Unhandled exception. System.MissingMethodException: Method not found: 'MQTTnet.Diagnostics.IMqttNetLogger MQTTnet.Diagnostics.IMqttNetLogger.CreateChildLogger(System.String)'.
Jun 22 17:58:09  docker[14365]:    at MQTTnet.Extensions.ManagedClient.ManagedMqttClient..ctor(IMqttClient mqttClient, IMqttNetLogger logger)
Jun 22 17:58:09  docker[14365]:    at MQTTnet.Extensions.ManagedClient.MqttFactoryExtensions.CreateManagedMqttClient(IMqttFactory factory)
Jun 22 17:58:09  docker[14365]:    at Zigbee2MqttAssistant.Services.MqttConnectionService.Connect() in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 117
Jun 22 17:58:09  docker[14365]:    at Zigbee2MqttAssistant.Services.MqttConnectionService.StartAsync(CancellationToken ct) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 62
Jun 22 17:58:09  docker[14365]:    at Microsoft.AspNetCore.Hosting.HostedServiceExecutor.ExecuteAsync(Func`2 callback, Boolean throwOnFirstFailure)
Jun 22 17:58:09  docker[14365]:    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
Jun 22 17:58:09  docker[14365]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
Jun 22 17:58:09  docker[14365]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
Jun 22 17:58:09  docker[14365]:    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host) 
Jun 22 17:58:09  docker[14365]:    at Zigbee2MqttAssistant.Program.Main(String[] args) in d:\a\1\s\Zigbee2MqttAssistant\Program.cs:line 15
Jun 22 17:58:10  systemd[1]: zigbee2mqttassistant.service: Main process exited, code=exited, status=139/n/a
Jun 22 17:58:10  docker[14507]: zigbee2mqttassistant
Jun 22 17:58:10  systemd[1]: zigbee2mqttassistant.service: Failed with result 'exit-code'.
Jun 22 17:58:13  systemd[1]: zigbee2mqttassistant.service: Scheduled restart job, restart counter is at 4.
```
I never had this issue with previous versions. I revert back to "0.3.171-377-linux-arm64" and it works again. 

What you you need to investigate this?

I am running Zigbee2mqtt dev latest on docker (intel 64 bit nuc)

**Comment by munklinde** [comment]
I'm using zigbee2mqtt & the UI as plugins installed from Hassio Supervisor. How do I roll back to the suggested version ?

**Comment by EpicLPer** [comment]
Same, addon will just shutdown after that.

**Comment by ademobile** [comment]
Having the same issue

**Comment by IonutNeagu** [comment]
Same issue

**Comment by Hotabka** [comment]
Same

**Comment by Heronimonimo** [comment]
Same problem here.

@carldebilly could you fix this by updating or reverting the MQTT dependencies?

**Comment by tdn131** [comment]
I have the same problem with multiple devices. Version 0.3.173 doesn't work, while 0.3.170 does. I reverted using a backup of Home Assistant and only restoring Zigbee2MQTTAssistant.

**Comment by carldebilly** [comment]
Sorry for the bug.  Should be fixed in the next version.

**Comment by carldebilly** [comment]
Fixed!  Sorry for the delay.

**Comment by tedsluis** [comment]
@carldebilly Thanks!
