### ISSUE TITLE
Can't make connection with mqtt

### ISSUE THREAD

**Issue by Stephan296** [yllibed/Zigbee2MqttAssistant#3]
I have insert the right mqtt server details and credentials (zigbee2mqtt works perfect on this credentials) but i get still the same error:

```
      Unable to connect to MQTT server mqtt://homeassistant.
MQTTnet.Exceptions.MqttCommunicationException: No such device or address ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.ResolveCallback(Object context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoDnsCallback(IAsyncResult result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.DnsCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync()
```

**Comment by carldebilly** [comment]
Few questions...
1. Which MQTT package are you using? Is it integrated with HASS.IO?
2. From your PC, can you ping the name of your mqtt server?
3. If you try using the IP address instead, does it works?
4. Are you using a secured version? Any unusual port?
5. By reading the error message, it looks like the name is "`homeassistant.`" (with a dot at the end).
   What kind of DNS do you have in your network? Is it able to resolve this name?

**Comment by carldebilly** [comment]
I think I found your problem: don't use the _URI_ format. Your setting should be something like this:

```
{
  "settings": {
    "mqttserver": "homeassistant",
    "mqttusername": "user",
    "mqttpassword": "password"
  }
}
```

Make sure you're not prefixing the `mqttserver` with `mqtt://`.
