### ISSUE TITLE
[BUG] Issue with Sonoff SNZB-02 unresponsive

### ISSUE THREAD

**Issue by buzzard10** [yllibed/Zigbee2MqttAssistant#398]
# Describe the bug
I buyed zigbee stick and i don't know why, other sonoff devices works great, but there is a problem with keeping connection with snzb-02 temperature sensor alive. I can connect sensor to Home Assistant, but unfortunatelly after that device is going dark and device is not showing in HA devices tab. In zigbee2mqttassistant i can see only that device was online for example 2 hours. 

## To Reproduce
1. Connect sonoff snzb-02 device to ha
2. Wait ~10-20 minutes

**Expected behavior**
Sensor should be available as other sonoff devices

## Steps I took to try resolve the problem
I removed device and connected again(three times), i added paper to battery, to make sure that there is no issue with battery

## Installation
 - Version of Zigbee2MqttAssistant (this software): 0.3.157
 - Version of Zigbee2Mqtt: 1.20.0
 - Installation type (HASS.IO, Docker...): HASS.IO/superviser?

## Pertinent logs
I don't know where i can find logs for this issue

**Comment by buzzard10** [comment]
I found this in logs:
`Exception in async_discover when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'device': {'identifiers': ['zigbee2mqtt_XXXXXXXXXXXXXXXX'], 'manufacturer': 'SONOFF', 'model': 'Temperature and humidity sensor (SNZB-02)', 'name': 'Temperature Sensor XXXXXXXXXXXXXXXX', 'sw_version': 'Zigbee2MQTT 1.20.0'}, 'device_class': 'battery', 'json_attributes_topic': 'zigbee2mqtt/Temperature Sensor XXXXXXXXXXXXXXXX', 'name': 'Temperature Sensor XXXXXXXXXXXXXXXX battery', 'state_class': 'measurement', 'state_topic': 'zigbee2mqtt/Temperature Sensor XXXXXXXXXXXXXXXX', 'unique_id': 'XXXXXXXXXXXXXXXX_battery_zigbee2mqtt', 'unit_of_measurement': '%', 'value_template': '{{ value_json.battery }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 152, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['state_class']`
